---

- name: Run the FreeIPA Replica installer
  args:
    creates: /etc/ipa/custodia/custodia.conf
  command: >
    {{ freeipa_replica_install_base_command }}
    {{ freeipa_replica_install_options | join(' ') }}
